// GENERATED by scripts/generate-movers-data.ts -- do not edit by hand.
/** Emoji icon per Movers word set. */
export const MOVERS_WORD_SET_ICONS: Record<string, string> = {
  'movers-animals': '🦋',
  'movers-body': '✋',
  'movers-family': '👨‍👩‍👧',
  'movers-food': '🍎',
  'movers-health': '🩹',
  'movers-home': '🏠',
  'movers-names': '🙋',
  'movers-nature': '🌍',
  'movers-places': '🏙️',
  'movers-school': '🏫',
  'movers-sports': '⚽',
  'movers-time': '🕐',
  'movers-transport': '🚂',
  'movers-weather': '⛈️',
  'movers-work': '👷',
  'movers-verbs': '🏃',
  'movers-adjectives': '🌈',
  'movers-words': '🔤',
};
