// GENERATED by scripts/generate-movers-data.ts -- do not edit by hand.
// Hand-tune a word through scripts/data/movers-overrides.json instead.
import type { WordSet, Word } from '@/shared/types';
import moversAnimals from './movers-animals.json';
import moversBody from './movers-body.json';
import moversFamily from './movers-family.json';
import moversFood from './movers-food.json';
import moversHealth from './movers-health.json';
import moversHome from './movers-home.json';
import moversNames from './movers-names.json';
import moversNature from './movers-nature.json';
import moversPlaces from './movers-places.json';
import moversSchool from './movers-school.json';
import moversSports from './movers-sports.json';
import moversTime from './movers-time.json';
import moversTransport from './movers-transport.json';
import moversWeather from './movers-weather.json';
import moversWork from './movers-work.json';
import moversVerbs from './movers-verbs.json';
import moversAdjectives from './movers-adjectives.json';
import moversWords from './movers-words.json';

export const moversWordSetRegistry: WordSet[] = [
  { id: 'movers-animals', displayName: 'Animals', words: moversAnimals as Word[] },
  { id: 'movers-body', displayName: 'Body & Clothes', words: moversBody as Word[] },
  { id: 'movers-family', displayName: 'Family & Friends', words: moversFamily as Word[] },
  { id: 'movers-food', displayName: 'Food & Drink', words: moversFood as Word[] },
  { id: 'movers-health', displayName: 'Health', words: moversHealth as Word[] },
  { id: 'movers-home', displayName: 'Home', words: moversHome as Word[] },
  { id: 'movers-names', displayName: 'Names', words: moversNames as Word[] },
  { id: 'movers-nature', displayName: 'World & Nature', words: moversNature as Word[] },
  { id: 'movers-places', displayName: 'Places & Directions', words: moversPlaces as Word[] },
  { id: 'movers-school', displayName: 'School', words: moversSchool as Word[] },
  { id: 'movers-sports', displayName: 'Sports & Leisure', words: moversSports as Word[] },
  { id: 'movers-time', displayName: 'Time', words: moversTime as Word[] },
  { id: 'movers-transport', displayName: 'Transport', words: moversTransport as Word[] },
  { id: 'movers-weather', displayName: 'Weather', words: moversWeather as Word[] },
  { id: 'movers-work', displayName: 'Work & Jobs', words: moversWork as Word[] },
  { id: 'movers-verbs', displayName: 'Action Words', words: moversVerbs as Word[] },
  { id: 'movers-adjectives', displayName: 'Describing Words', words: moversAdjectives as Word[] },
  { id: 'movers-words', displayName: 'More Words', words: moversWords as Word[] },
];

export function getMoversWordSet(id: string): WordSet | undefined {
  return moversWordSetRegistry.find((ws) => ws.id === id);
}
