/**
 * How each Movers word gets its picture. Hand-authored, one line per word.
 *
 * This is where the human judgement lives. The generator hard-fails on a
 * missing entry rather than guessing, because the guess that matters -- "is
 * there a real picture for this word?" -- decides whether the word may appear
 * in a picture-choice or type-the-word round at all. A silent default is how a
 * card showing the written word ends up as the answer to "which picture?".
 *
 * Run `npm run gen:movers -- --stub` to print paste-ready lines for anything
 * missing, pre-guessed by part of speech.
 *
 * Choosing a tier:
 *   emoji      a single Noto glyph a child reads as the word. First choice.
 *   scene      two glyphs arranged to show a relationship (above, into).
 *   shared     the word is already taught at Starters *in the same sense*, so
 *              it reuses that asset instead of generating a duplicate.
 *   ai         concrete, but no glyph comes close. Needs FAL_KEY.
 *   word-card  genuinely unpicturable. Marks the word `pictorial: false`.
 *
 * `shared` is opt-in per word rather than automatic on a matching filename,
 * because homographs cross the levels: Starters `bat` is a cricket bat, Movers
 * `bat` is the animal. Sharing by name alone would have shipped the wrong
 * picture for that word and several like it.
 */
import type { ScenePlacement } from './movers-renderers.ts';

export type PictureSpec =
  | { kind: 'emoji'; emoji: string }
  | { kind: 'scene'; subject: string; anchor: string; placement: ScenePlacement }
  | { kind: 'shared' }
  | { kind: 'ai' }
  | { kind: 'word-card' };

/**
 * The cat and the box the vertical position scenes are built from.
 *
 * Only `above` and `below` are drawn this way. Two static emoji can express a
 * vertical relationship unambiguously, but not much else: `near`, `outside`,
 * `opposite`, `into` and `out of` all reduce to "box on the left, cat on the
 * right" and rendered identically when they were tried. Identical pictures are
 * worse than none -- they make several words the right answer to the same
 * picture round -- so the rest are honest word cards.
 */
const CAT = '🐱';
const BOX = '📦';
const scene = (placement: ScenePlacement): PictureSpec => ({
  kind: 'scene',
  subject: CAT,
  anchor: BOX,
  placement,
});

/** A compound word drawn as its two ideas side by side. */
const pair = (anchor: string, subject: string): PictureSpec => ({
  kind: 'scene',
  subject,
  anchor,
  placement: 'pair',
});

export const MOVERS_PICTURES: Readonly<Record<string, PictureSpec>> = {
  // ── Animals ───────────────────────────────────────────────────────────────
  // `bat` is deliberately NOT shared: Starters teaches the cricket bat.
  bat: { kind: 'emoji', emoji: '🦇' },
  cage: { kind: 'ai' },
  dolphin: { kind: 'emoji', emoji: '🐬' },
  fly: { kind: 'emoji', emoji: '🪰' },
  kangaroo: { kind: 'shared' },
  kitten: { kind: 'emoji', emoji: '🐈' },
  lion: { kind: 'shared' },
  panda: { kind: 'shared' },
  parrot: { kind: 'shared' },
  penguin: { kind: 'shared' },
  puppy: { kind: 'emoji', emoji: '🐕' },
  rabbit: { kind: 'shared' },
  shark: { kind: 'shared' },
  snail: { kind: 'emoji', emoji: '🐌' },
  whale: { kind: 'shared' },

  // ── Body & Clothes ────────────────────────────────────────────────────────
  back: { kind: 'shared' },
  beard: { kind: 'emoji', emoji: '🧔' },
  blond: { kind: 'emoji', emoji: '👱' },
  coat: { kind: 'emoji', emoji: '🧥' },
  curly: { kind: 'emoji', emoji: '👩‍🦱' },
  fair: { kind: 'ai' },
  fat: { kind: 'ai' },
  helmet: { kind: 'emoji', emoji: '⛑️' },
  moustache: { kind: 'emoji', emoji: '🥸' },
  neck: { kind: 'ai' },
  scarf: { kind: 'emoji', emoji: '🧣' },
  shoulder: { kind: 'ai' },
  stomach: { kind: 'ai' },
  sweater: { kind: 'shared' },
  swimsuit: { kind: 'emoji', emoji: '🩱' },
  thin: { kind: 'ai' },
  tooth: { kind: 'shared' },

  // ── Family & Friends ──────────────────────────────────────────────────────
  age: { kind: 'emoji', emoji: '🎂' },
  aunt: { kind: 'ai' },
  daughter: { kind: 'emoji', emoji: '👧' },
  granddaughter: { kind: 'ai' },
  grandparent: { kind: 'emoji', emoji: '👴' },
  grandson: { kind: 'ai' },
  'grown-up': { kind: 'emoji', emoji: '🧑' },
  parent: { kind: 'emoji', emoji: '👪' },
  son: { kind: 'emoji', emoji: '👦' },
  uncle: { kind: 'ai' },

  // ── Food & Drink ──────────────────────────────────────────────────────────
  bottle: { kind: 'emoji', emoji: '🍼' },
  bowl: { kind: 'emoji', emoji: '🥣' },
  cheese: { kind: 'shared' },
  coffee: { kind: 'shared' },
  cup: { kind: 'emoji', emoji: '☕' },
  glass: { kind: 'emoji', emoji: '🥛' },
  hungry: { kind: 'ai' },
  milkshake: { kind: 'emoji', emoji: '🥤' },
  noodles: { kind: 'emoji', emoji: '🍜' },
  pancake: { kind: 'emoji', emoji: '🥞' },
  pasta: { kind: 'emoji', emoji: '🍝' },
  picnic: { kind: 'emoji', emoji: '🧺' },
  plate: { kind: 'emoji', emoji: '🍽️' },
  salad: { kind: 'shared' },
  sandwich: { kind: 'shared' },
  sauce: { kind: 'emoji', emoji: '🧂' },
  soup: { kind: 'shared' },
  tea: { kind: 'shared' },
  thirsty: { kind: 'ai' },
  vegetable: { kind: 'emoji', emoji: '🥦' },

  // ── Health ────────────────────────────────────────────────────────────────
  cold: { kind: 'emoji', emoji: '🤧' },
  cough: { kind: 'emoji', emoji: '😷' },
  cry: { kind: 'emoji', emoji: '😢' },
  earache: { kind: 'emoji', emoji: '👂' },
  fall: { kind: 'ai' },
  fine: { kind: 'emoji', emoji: '😊' },
  headache: { kind: 'emoji', emoji: '🤕' },
  ill: { kind: 'emoji', emoji: '🤒' },
  matter: { kind: 'word-card' },
  sick: { kind: 'emoji', emoji: '🤢' },
  'stomach-ache': { kind: 'emoji', emoji: '😣' },
  temperature: { kind: 'emoji', emoji: '🌡️' },
  tired: { kind: 'emoji', emoji: '😴' },
  toothache: { kind: 'emoji', emoji: '🦷' },

  // ── Home ──────────────────────────────────────────────────────────────────
  address: { kind: 'emoji', emoji: '✉️' },
  balcony: { kind: 'ai' },
  basement: { kind: 'ai' },
  blanket: { kind: 'shared' },
  downstairs: { kind: 'ai' },
  dream: { kind: 'emoji', emoji: '💭' },
  elevator: { kind: 'emoji', emoji: '🛗' },
  floor: { kind: 'shared' },
  internet: { kind: 'emoji', emoji: '🌐' },
  lift: { kind: 'emoji', emoji: '🛗' },
  machine: { kind: 'emoji', emoji: '⚙️' },
  message: { kind: 'emoji', emoji: '💬' },
  roof: { kind: 'ai' },
  seat: { kind: 'emoji', emoji: '💺' },
  shower: { kind: 'emoji', emoji: '🚿' },
  stair: { kind: 'ai' },
  toothbrush: { kind: 'emoji', emoji: '🪥' },
  toothpaste: { kind: 'ai' },
  upstairs: { kind: 'ai' },
  wash: { kind: 'emoji', emoji: '🧼' },

  // ── Names ─────────────────────────────────────────────────────────────────
  // A name is a spelling to recognise, not a thing to picture.
  Charlie: { kind: 'word-card' },
  Clare: { kind: 'word-card' },
  Daisy: { kind: 'word-card' },
  Fred: { kind: 'word-card' },
  Jack: { kind: 'word-card' },
  Jane: { kind: 'word-card' },
  Jim: { kind: 'word-card' },
  Julia: { kind: 'word-card' },
  Lily: { kind: 'word-card' },
  Mary: { kind: 'word-card' },
  Paul: { kind: 'word-card' },
  Peter: { kind: 'word-card' },
  Sally: { kind: 'word-card' },
  Vicky: { kind: 'word-card' },
  Zoe: { kind: 'word-card' },

  // ── World & Nature ────────────────────────────────────────────────────────
  building: { kind: 'emoji', emoji: '🏢' },
  city: { kind: 'emoji', emoji: '🌆' },
  country: { kind: 'emoji', emoji: '🗺️' },
  countryside: { kind: 'emoji', emoji: '🌄' },
  field: { kind: 'emoji', emoji: '🌾' },
  forest: { kind: 'emoji', emoji: '🌲' },
  grass: { kind: 'emoji', emoji: '🌿' },
  ground: { kind: 'ai' },
  island: { kind: 'emoji', emoji: '🏝️' },
  jungle: { kind: 'emoji', emoji: '🌴' },
  lake: { kind: 'emoji', emoji: '🏞️' },
  leaf: { kind: 'emoji', emoji: '🍃' },
  moon: { kind: 'shared' },
  mountain: { kind: 'emoji', emoji: '⛰️' },
  plant: { kind: 'shared' },
  river: { kind: 'ai' },
  road: { kind: 'emoji', emoji: '🛣️' },
  rock: { kind: 'emoji', emoji: '🪨' },
  sky: { kind: 'ai' },
  star: { kind: 'shared' },
  town: { kind: 'shared' },
  village: { kind: 'emoji', emoji: '🏘️' },
  waterfall: { kind: 'ai' },
  wave: { kind: 'emoji', emoji: '🌊' },
  world: { kind: 'emoji', emoji: '🌏' },

  // ── Places & Directions ───────────────────────────────────────────────────
  above: scene('above'),
  below: scene('below'),
  bottom: { kind: 'word-card' },
  café: { kind: 'emoji', emoji: '🍰' },
  'car park': { kind: 'emoji', emoji: '🅿️' },
  centre: { kind: 'emoji', emoji: '🎯' },
  circle: { kind: 'emoji', emoji: '⭕' },
  'city centre': pair('🌆', '🎯'),
  farm: { kind: 'shared' },
  funfair: { kind: 'emoji', emoji: '🎡' },
  inside: { kind: 'word-card' },
  library: { kind: 'emoji', emoji: '📚' },
  map: { kind: 'emoji', emoji: '🗺️' },
  market: { kind: 'shared' },
  near: { kind: 'word-card' },
  opposite: { kind: 'word-card' },
  outside: { kind: 'word-card' },
  place: { kind: 'emoji', emoji: '📍' },
  'shopping centre': { kind: 'emoji', emoji: '🏬' },
  square: { kind: 'emoji', emoji: '🟦' },
  straight: { kind: 'emoji', emoji: '⬆️' },
  supermarket: { kind: 'emoji', emoji: '🛒' },
  top: { kind: 'word-card' },
  'town centre': pair('🏙️', '📍'),

  // ── School ────────────────────────────────────────────────────────────────
  app: { kind: 'emoji', emoji: '📱' },
  break: { kind: 'emoji', emoji: '🛝' },
  'e-book': { kind: 'emoji', emoji: '📖' },
  homework: { kind: 'emoji', emoji: '📝' },
  hundred: { kind: 'emoji', emoji: '💯' },
  laptop: { kind: 'emoji', emoji: '💻' },
  mistake: { kind: 'emoji', emoji: '❌' },
  pair: { kind: 'emoji', emoji: '🧦' },
  shape: { kind: 'emoji', emoji: '🔷' },
  teach: { kind: 'emoji', emoji: '🧑‍🏫' },
  website: { kind: 'emoji', emoji: '🖥️' },

  // ── Sports & Leisure ──────────────────────────────────────────────────────
  band: { kind: 'emoji', emoji: '🎸' },
  CD: { kind: 'emoji', emoji: '💿' },
  cinema: { kind: 'shared' },
  comic: pair('📖', '😂'),
  'comic book': pair('📖', '💥'),
  dance: { kind: 'emoji', emoji: '💃' },
  DVD: { kind: 'emoji', emoji: '📀' },
  email: { kind: 'emoji', emoji: '📧' },
  film: { kind: 'emoji', emoji: '🎬' },
  fish: { kind: 'emoji', emoji: '🎣' },
  'go shopping': { kind: 'emoji', emoji: '🛍️' },
  goal: { kind: 'emoji', emoji: '🥅' },
  holiday: { kind: 'emoji', emoji: '🏖️' },
  hop: { kind: 'emoji', emoji: '🐇' },
  'ice skates': { kind: 'emoji', emoji: '⛸️' },
  'ice skating': pair('⛸️', '🧊'),
  kick: { kind: 'emoji', emoji: '🦵' },
  model: { kind: 'ai' },
  movie: { kind: 'emoji', emoji: '🍿' },
  net: { kind: 'emoji', emoji: '🕸️' },
  party: { kind: 'emoji', emoji: '🎉' },
  player: { kind: 'emoji', emoji: '⛹️' },
  pool: { kind: 'ai' },
  practice: { kind: 'ai' },
  practise: { kind: 'ai' },
  present: { kind: 'emoji', emoji: '🎁' },
  'roller skates': { kind: 'emoji', emoji: '🛼' },
  'roller skating': pair('🛼', '🛣️'),
  sail: { kind: 'emoji', emoji: '⛵' },
  score: { kind: 'ai' },
  shopping: { kind: 'ai' },
  skate: { kind: 'ai' },
  skip: { kind: 'emoji', emoji: '🤸' },
  'sports centre': pair('⚽', '🏢'),
  swim: { kind: 'emoji', emoji: '🏊' },
  'swimming pool': pair('🏊', '🟦'),
  text: { kind: 'ai' },
  towel: { kind: 'emoji', emoji: '🧻' },
  treasure: { kind: 'emoji', emoji: '💎' },
  video: { kind: 'emoji', emoji: '📹' },
  walk: { kind: 'emoji', emoji: '🚶' },

  // ── Time ──────────────────────────────────────────────────────────────────
  after: { kind: 'word-card' },
  always: { kind: 'word-card' },
  before: { kind: 'word-card' },
  every: { kind: 'word-card' },
  Friday: { kind: 'word-card' },
  Monday: { kind: 'word-card' },
  never: { kind: 'word-card' },
  "o'clock": { kind: 'emoji', emoji: '🕐' },
  Saturday: { kind: 'word-card' },
  sometimes: { kind: 'word-card' },
  Sunday: { kind: 'word-card' },
  Thursday: { kind: 'word-card' },
  Tuesday: { kind: 'word-card' },
  Wednesday: { kind: 'word-card' },
  week: { kind: 'emoji', emoji: '📅' },
  weekend: { kind: 'emoji', emoji: '🗓️' },
  yesterday: { kind: 'word-card' },

  // ── Transport ─────────────────────────────────────────────────────────────
  'bus station': pair('🚌', '🚉'),
  'bus stop': { kind: 'emoji', emoji: '🚏' },
  drive: { kind: 'emoji', emoji: '🚙' },
  ride: { kind: 'emoji', emoji: '🚴' },
  station: { kind: 'shared' },
  ticket: { kind: 'emoji', emoji: '🎫' },
  tractor: { kind: 'shared' },
  trip: { kind: 'emoji', emoji: '🧳' },

  // ── Weather ───────────────────────────────────────────────────────────────
  cloud: { kind: 'shared' },
  cloudy: { kind: 'emoji', emoji: '☁️' },
  ice: { kind: 'shared' },
  rain: { kind: 'shared' },
  rainbow: { kind: 'shared' },
  snow: { kind: 'shared' },
  sunny: { kind: 'emoji', emoji: '🌞' },
  weather: { kind: 'emoji', emoji: '🌦️' },
  wind: { kind: 'shared' },
  windy: { kind: 'emoji', emoji: '🎐' },

  // ── Work & Jobs ───────────────────────────────────────────────────────────
  circus: { kind: 'emoji', emoji: '🎪' },
  clown: { kind: 'shared' },
  cook: { kind: 'shared' },
  dentist: { kind: 'emoji', emoji: '🪥' },
  doctor: { kind: 'shared' },
  driver: { kind: 'emoji', emoji: '🚕' },
  farmer: { kind: 'shared' },
  'film star': pair('🎬', '⭐'),
  hospital: { kind: 'shared' },
  nurse: { kind: 'shared' },
  pirate: { kind: 'emoji', emoji: '🏴‍☠️' },
  'pop star': { kind: 'emoji', emoji: '🎤' },
  work: { kind: 'emoji', emoji: '💼' },

  // ── Describing words ──────────────────────────────────────────────────────
  afraid: { kind: 'emoji', emoji: '😨' },
  all: { kind: 'word-card' },
  'all right': { kind: 'emoji', emoji: '👌' },
  asleep: { kind: 'emoji', emoji: '😪' },
  awake: { kind: 'ai' },
  bad: { kind: 'emoji', emoji: '👎' },
  best: { kind: 'emoji', emoji: '🏆' },
  better: { kind: 'word-card' },
  boring: { kind: 'emoji', emoji: '🥱' },
  brave: { kind: 'emoji', emoji: '🦸' },
  brilliant: { kind: 'emoji', emoji: '🌟' },
  busy: { kind: 'ai' },
  careful: { kind: 'ai' },
  clever: { kind: 'emoji', emoji: '🤓' },
  dangerous: { kind: 'emoji', emoji: '⚠️' },
  different: { kind: 'ai' },
  difficult: { kind: 'ai' },
  easy: { kind: 'ai' },
  exciting: { kind: 'emoji', emoji: '🤩' },
  famous: { kind: 'ai' },
  first: { kind: 'emoji', emoji: '🥇' },
  frightened: { kind: 'emoji', emoji: '😱' },
  hot: { kind: 'emoji', emoji: '🔥' },
  huge: { kind: 'ai' },
  last: { kind: 'word-card' },
  little: { kind: 'ai' },
  loud: { kind: 'emoji', emoji: '📢' },
  naughty: { kind: 'emoji', emoji: '😈' },
  pretty: { kind: 'emoji', emoji: '🌸' },
  quick: { kind: 'ai' },
  quiet: { kind: 'emoji', emoji: '🤫' },
  round: { kind: 'emoji', emoji: '🔵' },
  safe: { kind: 'emoji', emoji: '🦺' },
  second: { kind: 'emoji', emoji: '🥈' },
  slow: { kind: 'ai' },
  strong: { kind: 'emoji', emoji: '💪' },
  surprised: { kind: 'emoji', emoji: '😲' },
  sweet: { kind: 'shared' },
  tall: { kind: 'ai' },
  terrible: { kind: 'emoji', emoji: '😖' },
  third: { kind: 'emoji', emoji: '🥉' },
  weak: { kind: 'ai' },
  well: { kind: 'ai' },
  wet: { kind: 'emoji', emoji: '💦' },
  worse: { kind: 'word-card' },
  worst: { kind: 'word-card' },
  wrong: { kind: 'emoji', emoji: '❌' },

  // ── Action words ──────────────────────────────────────────────────────────
  'be called': { kind: 'ai' },
  bring: { kind: 'ai' },
  build: { kind: 'emoji', emoji: '🏗️' },
  buy: { kind: 'emoji', emoji: '💳' },
  call: { kind: 'emoji', emoji: '📞' },
  carry: { kind: 'ai' },
  catch: { kind: 'ai' },
  change: { kind: 'emoji', emoji: '🔄' },
  climb: { kind: 'emoji', emoji: '🧗' },
  could: { kind: 'word-card' },
  'dress up': { kind: 'ai' },
  drop: { kind: 'ai' },
  dry: { kind: 'ai' },
  feed: { kind: 'ai' },
  fix: { kind: 'emoji', emoji: '🔧' },
  'get dressed': { kind: 'ai' },
  'get off': { kind: 'ai' },
  'get on': { kind: 'ai' },
  'get undressed': { kind: 'ai' },
  'get up': { kind: 'emoji', emoji: '⏰' },
  grow: { kind: 'emoji', emoji: '🌱' },
  'have to': { kind: 'word-card' },
  help: { kind: 'emoji', emoji: '🤝' },
  hide: { kind: 'emoji', emoji: '🙈' },
  hurt: { kind: 'emoji', emoji: '🤕' },
  invite: { kind: 'emoji', emoji: '💌' },
  'look for': { kind: 'emoji', emoji: '🔍' },
  lose: { kind: 'ai' },
  mean: { kind: 'word-card' },
  move: { kind: 'ai' },
  must: { kind: 'word-card' },
  need: { kind: 'word-card' },
  'put on': { kind: 'ai' },
  send: { kind: 'emoji', emoji: '📤' },
  shall: { kind: 'word-card' },
  shop: { kind: 'shared' },
  shout: { kind: 'emoji', emoji: '🗣️' },
  take: { kind: 'ai' },
  'take off': { kind: 'ai' },
  think: { kind: 'emoji', emoji: '🤔' },
  travel: { kind: 'emoji', emoji: '✈️' },
  wait: { kind: 'emoji', emoji: '⏳' },
  wake: { kind: 'ai' },
  water: { kind: 'shared' },
  would: { kind: 'word-card' },

  // ── More words ────────────────────────────────────────────────────────────
  along: { kind: 'word-card' },
  another: { kind: 'word-card' },
  any: { kind: 'word-card' },
  around: { kind: 'word-card' },
  at: { kind: 'word-card' },
  badly: { kind: 'word-card' },
  because: { kind: 'word-card' },
  both: { kind: 'word-card' },
  by: { kind: 'word-card' },
  carefully: { kind: 'word-card' },
  'come on': { kind: 'word-card' },
  difference: { kind: 'word-card' },
  down: { kind: 'word-card' },
  everyone: { kind: 'word-card' },
  everything: { kind: 'word-card' },
  'excuse me': { kind: 'word-card' },
  how: { kind: 'word-card' },
  'how much': { kind: 'word-card' },
  'how often': { kind: 'word-card' },
  idea: { kind: 'emoji', emoji: '💡' },
  into: { kind: 'word-card' },
  kind: { kind: 'word-card' },
  laugh: { kind: 'emoji', emoji: '😂' },
  loudly: { kind: 'word-card' },
  more: { kind: 'word-card' },
  most: { kind: 'word-card' },
  noise: { kind: 'emoji', emoji: '🔊' },
  nothing: { kind: 'word-card' },
  off: { kind: 'word-card' },
  often: { kind: 'word-card' },
  on: { kind: 'word-card' },
  only: { kind: 'word-card' },
  out: { kind: 'word-card' },
  'out of': { kind: 'word-card' },
  quickly: { kind: 'word-card' },
  quietly: { kind: 'word-card' },
  slowly: { kind: 'word-card' },
  someone: { kind: 'word-card' },
  something: { kind: 'word-card' },
  than: { kind: 'word-card' },
  then: { kind: 'word-card' },
  up: { kind: 'word-card' },
  when: { kind: 'word-card' },
  where: { kind: 'word-card' },
  which: { kind: 'word-card' },
  who: { kind: 'word-card' },
  why: { kind: 'word-card' },
};
