/**
 * Generate the A1 Movers word sets from the extracted Cambridge wordlist.
 *
 *   npm run gen:movers                 write src/data/yle-movers/
 *   npm run gen:movers -- --dry-run    show what would change, write nothing
 *   npm run gen:movers -- --check      fail if the output on disk is stale (CI)
 *   npm run gen:movers -- --stub       print missing curation entries
 *   npm run gen:movers -- --only=movers-animals,movers-verbs
 *   npm run gen:movers -- --force      overwrite a hand-edited file
 *
 * This script is IO only; every decision lives in `scripts/lib/movers-build.ts`,
 * which is pure and unit-tested. Re-extracting the PDF is a separate, rarely-run
 * step -- see `scripts/pdf/extract-movers-wordlist.py`.
 *
 * Output is byte-stable: same inputs, same bytes, so `--check` is a real
 * staleness gate rather than a formatting diff.
 */
import { createHash } from 'crypto';
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'fs';
import { join, resolve } from 'path';
import { buildMoversData, type MoversWordSet, type RawWordlist } from './lib/movers-build.ts';
import { MOVERS_PICTURES } from './lib/movers-pictures.ts';
import { MOVERS_TOPICS } from './lib/movers-topics.ts';
import { slug } from './lib/word-loader.ts';

const ROOT = resolve(import.meta.dirname, '..');
const RAW_PATH = join(ROOT, 'scripts/data/movers-wordlist.raw.json');
const STARTERS_DIR = join(ROOT, 'src/data/yle-starters');
const OUT_DIR = join(ROOT, 'src/data/yle-movers');
// Both live under scripts/, not beside the data: `src/data/yle-movers/` is
// globbed by the app and by other generators, which expect every .json in it to
// be an array of words. A manifest or an override map sitting there breaks them.
const MANIFEST = join(ROOT, 'scripts/data/movers-manifest.json');
const OVERRIDES = join(ROOT, 'scripts/data/movers-overrides.json');

const args = process.argv.slice(2);
const has = (flag: string) => args.includes(flag);
const dryRun = has('--dry-run');
const check = has('--check');
const force = has('--force');
const stubOnly = has('--stub');
const only = args.find((a) => a.startsWith('--only='))?.slice('--only='.length).split(',');

const sha = (text: string) => createHash('sha256').update(text).digest('hex');
const serialize = (value: unknown) => `${JSON.stringify(value, null, 2)}\n`;

function readStarters(): { texts: Set<string>; slugs: Set<string> } {
  const texts = new Set<string>();
  const slugs = new Set<string>();
  for (const file of readdirSync(STARTERS_DIR).filter((f) => f.endsWith('.json'))) {
    const words: Array<{ text: string }> = JSON.parse(
      readFileSync(join(STARTERS_DIR, file), 'utf-8'),
    );
    for (const word of words) {
      texts.add(word.text.toLowerCase());
      slugs.add(slug(word.text));
    }
  }
  return { texts, slugs };
}

/** `index.ts`, mirroring the Starters registry so consumers look identical. */
function renderIndex(sets: MoversWordSet[]): string {
  const imports = sets
    .map((set) => `import ${camel(set.id)} from './${set.id}.json';`)
    .join('\n');
  const rows = sets
    .map(
      (set) =>
        `  { id: '${set.id}', displayName: '${set.displayName}', ` +
        `words: ${camel(set.id)} as Word[] },`,
    )
    .join('\n');

  return `// GENERATED by scripts/generate-movers-data.ts -- do not edit by hand.
// Hand-tune a word through scripts/data/movers-overrides.json instead.
import type { WordSet, Word } from '@/shared/types';
${imports}

export const moversWordSetRegistry: WordSet[] = [
${rows}
];

export function getMoversWordSet(id: string): WordSet | undefined {
  return moversWordSetRegistry.find((ws) => ws.id === id);
}
`;
}

/** `icons.ts`, mirroring the Starters shape. */
function renderIcons(sets: MoversWordSet[]): string {
  const rows = sets
    .map((set) => `  '${set.id}': '${MOVERS_TOPICS.find((t) => t.id === set.id)!.icon}',`)
    .join('\n');
  return `// GENERATED by scripts/generate-movers-data.ts -- do not edit by hand.
/** Emoji icon per Movers word set. */
export const MOVERS_WORD_SET_ICONS: Record<string, string> = {
${rows}
};
`;
}

const camel = (id: string) =>
  id.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase()).replace(/^movers/, 'movers');

function main(): number {
  const raw: RawWordlist = JSON.parse(readFileSync(RAW_PATH, 'utf-8'));
  const { texts, slugs } = readStarters();
  const overrides = existsSync(OVERRIDES) ? JSON.parse(readFileSync(OVERRIDES, 'utf-8')) : {};
  const aiRenderable = Boolean(process.env.FAL_KEY);

  const result = buildMoversData({
    raw,
    pictures: MOVERS_PICTURES,
    overrides,
    startersTexts: texts,
    startersSlugs: slugs,
    aiRenderable,
  });

  if (stubOnly) {
    console.log(result.stubs.length ? result.stubs.join('\n') : 'Nothing missing.');
    return 0;
  }

  for (const warning of result.warnings) console.warn(`  warning: ${warning}`);

  if (result.errors.length > 0) {
    console.error(`\n${result.errors.length} error(s); nothing written:`);
    for (const error of result.errors) console.error(`  - ${error}`);
    if (result.stubs.length) {
      console.error(`\nRun with --stub for paste-ready MOVERS_PICTURES entries.`);
    }
    return 1;
  }

  const sets = only ? result.sets.filter((set) => only.includes(set.id)) : result.sets;
  const files = new Map<string, string>(sets.map((set) => [`${set.id}.json`, serialize(set.words)]));
  // The registry and icons describe every set, so they are only correct when
  // the whole corpus was regenerated.
  if (!only) {
    files.set('index.ts', renderIndex(result.sets));
    files.set('icons.ts', renderIcons(result.sets));
  }

  const previous: Record<string, string> = existsSync(MANIFEST)
    ? JSON.parse(readFileSync(MANIFEST, 'utf-8'))
    : {};

  const stale: string[] = [];
  const edited: string[] = [];
  for (const [name, content] of files) {
    const path = join(OUT_DIR, name);
    if (existsSync(path)) {
      const onDisk = readFileSync(path, 'utf-8');
      if (onDisk === content) continue;
      // A file whose hash no longer matches the manifest was edited by hand;
      // overwriting it would throw that work away silently.
      if (previous[name] && sha(onDisk) !== previous[name]) edited.push(name);
    }
    stale.push(name);
  }

  if (check) {
    if (stale.length === 0) {
      console.log('Movers data is up to date.');
      return 0;
    }
    console.error(`Movers data is stale; run \`npm run gen:movers\`:`);
    for (const name of stale) console.error(`  - ${name}`);
    return 1;
  }

  if (edited.length > 0 && !force) {
    console.error(`These files were edited by hand since they were generated:`);
    for (const name of edited) console.error(`  - ${name}`);
    console.error(
      `\nMove the change into src/data/yle-movers/overrides.json, or pass --force ` +
        `to discard it.`,
    );
    return 1;
  }

  const total = result.sets.reduce((sum, set) => sum + set.words.length, 0);
  const nonPictorial = result.sets.reduce(
    (sum, set) => sum + set.words.filter((word) => word.pictorial === false).length,
    0,
  );

  if (dryRun) {
    console.log(`Would write ${stale.length} file(s):`);
    for (const name of stale) console.log(`  - ${name}`);
  } else {
    mkdirSync(OUT_DIR, { recursive: true });
    for (const name of stale) writeFileSync(join(OUT_DIR, name), files.get(name)!);
    const manifest = Object.fromEntries(
      [...files].map(([name, content]) => [name, sha(content)]),
    );
    writeFileSync(MANIFEST, serialize({ ...previous, ...manifest }));
    console.log(`Wrote ${stale.length} file(s) to src/data/yle-movers/`);
  }

  for (const set of result.sets) {
    const pictorial = set.words.filter((word) => word.pictorial !== false).length;
    console.log(
      `  ${set.id.padEnd(20)} ${String(set.words.length).padStart(3)} words` +
        `  ${String(pictorial).padStart(3)} with pictures`,
    );
  }
  console.log(
    `  ${'TOTAL'.padEnd(20)} ${String(total).padStart(3)} words` +
      `  ${String(total - nonPictorial).padStart(3)} with pictures` +
      `  (${result.reusedAssets.length} reuse Starters assets)`,
  );
  return 0;
}

process.exit(main());
